config/routes.rb
Rails.application.routes.draw do
  resources :favorites

  root "movies#index"
  
  resources :movies do
    resources :reviews  
  end
  
  resources :users
  get "sign-up" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "sign-in" => "sessions#new"

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :reviews, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_movies, through: :favorites, source: :movie

  validates :name, presence: true

  validates :email,
            presence: true,
            format: {
              with: /\A(\S+)@(.+)\.(\S+)\z/
            },
            uniqueness: {
              case_sensitive: false
            }

  validates :password, length: { minimum: 10, allow_blank: true }

  validates :username,
            presence: true,
            format: {
              with: /\A[a-zA-Z0-9]+\z/
            },
            uniqueness: {
              case_sensitive: true
            }
  def gravatar_id
    Digest::MD5.hexdigest(email.downcase)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_signin, except: [:new, :create]
  before_action :require_current_user, only: [:edit, :update, :destroy]

  def index
      @users = User.all
  end

  def show
      @user = User.find(params[:id])
      @reviews = @user.reviews
      @favorite_movies = @user.favorite_movies
  end

  def new
      @user = User.new
  end

  def create
      @user = User.new(user_params)
      if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user), notice: "Thanks for signing up!"
      else
        render :new, status: :unprocessable_entity

      end
  end

  def edit

  end

  def update

      if @user.update(user_params)
        redirect_to user_path(@user), notice: "Account successfully updated!"
      else
        render :edit, status: :unprocessable_entity
      end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, status: :see_other,
        alert: "Account successfully deleted!"
  end

  private

      def user_params
          params.require(:user).
          permit(:name, :email, :password, :password_confirmation, :username)
      end

      def require_current_user
        @user = User.find(params[:id])
        unless current_user?(@user)
          redirect_to root_url, status: :see_other
        end
      end

end

app/helpers/users_helper.rb
module UsersHelper
  def profile_image(user, size = 80)
    url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}?s=#{size}"
    image_tag(url, alt: user.name)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
    <%= render 'shared/errors', object: user %> 
    
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
    
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: "Alphanumeric characters only!" %>


    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :confirm_password, "Confrim Password" %>
    <%= f.password_field :confirm_password %>

   <% if user.new_record? %>
        <%= f.submit "Create Account" %>
    <% else %>
        <%= f.submit "Update Account" %>
    <% end %>
 
<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>
<%= render 'form' , user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<div class="container">
  <div class="form">
    <h1>Sign Up for an Account</h1>
    <%= render 'form', user: @user %>
  </div>

  <div class="mt-2">
    Already registerd? <%= link_to 'Sign-in', sign_in_path %>
  </div>
</div>

app/views/users/show.html.erb
<section class="user d-flex flex-column">
  <div class="d-flex flex-row">
    <div class="p-2 justify-content-center">
      <%= profile_image(@user) %>
    </div>
    <div class="p-2">
      <div class="d-flex flex-column ">
        <h1><%= @user.name %></h1>
        <h2><%= mail_to(@user.email) %></h2>
      </div>
    </div>
  </div>
  <p class="p-2">
    <%= @user.username %> <br>
    Member since - <%= @user.created_at.strftime("%B %Y") %>
  </p>
  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
      <%= link_to 'Delete Account', @user, class: "button delete",
                  data: { turbo_method: :delete, turbo_confirm: "Permanently delete your account!?" } %>
    </div>
    <% if @reviews.present? %>
      <h3>Reviews</h3>
      <% @reviews.each do |review| %>
        <div class="review">
          <div class="details">
            <span class="title">
              <%= link_to review.movie.title, review.movie %>
            </span>
            <%= pluralize(review.stars, 'star') %>
            <span class="date">
              <%= time_ago_in_words(review.created_at) %> ago
            </span>
            <p>
              <%= review.comment %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
    <% if @favorite_movies.present? %>
      <h3>Favorite Movies</h3>
      <div class="favorite-movies">
        <% @favorite_movies.each do |movie| %>
          <%= link_to image_tag(movie.image_file_name), movie %>
        <% end %>
      </div>
    <% end %>
</section>