config/routes.rb
Rails.application.routes.draw do
  resources :favorites

  root "movies#index"
  
  resources :movies do
    resources :reviews  
  end
  
  resources :users
  get "sign-up" => "users#new"

  resource :session, only: [:new, :create, :destroy]
  get "sign-in" => "sessions#new"

end

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
      <p class="copyritght">
         Copyright &copy; <%= Time.now.year %>
          <%= link_to "The Pragmatic Studio", "https://pragmaticstudio.com" %>
      </p>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav>
        <%= link_to image_tag("logo.png"), root_path() %>
        <ul class="left">
             <li> <%= link_to 'All Movies', movies_path() %> </li>
        </ul>
        <ul class="right">
          <% if current_user %>
               <li> <%= link_to current_user.name, current_user %> </li>
               <li class="button"> <%= link_to 'Sign out', session_path, 
                    data: { turbo_method: :delete }, class:"button" %>
               </li>
          <% else %>
               <li class="button"> <%= link_to 'Sign in', sign_in_path, class:"button" %></li>
               <li class="button"> <%= link_to 'Sign Up', sign_up_path, class:"button" %></li>
          <% end %>
        </ul>
   </nav>   
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Super-Heroic Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %> 

    <div class="content">
    <%= render  'layouts/flash'%>

     <%= yield %>
    </div>
    
    <%= render 'layouts/footer' %>
  </body>
</html>